### ISSUE TITLE
Please allow set_freq_corr() to use double for the ppm instead of the int

### ISSUE THREAD

**Issue by yarda** [dl1ksv/gr-funcube#5]
It seems this is just matter of changing the `int` to the `double`.

There is e.g. the gqrx bug about it:
https://github.com/gqrx-sdr/gqrx/issues/522

Which is badly opened against gqrx, because both gqrx and gr-osmosdr use double. The precision is lost upon conversion to the `int` in the gr-funcube. I can open PR.

**Comment by yarda** [comment]
The gr-osmosdr code (without the gr-funcube patch):
https://github.com/osmocom/gr-osmosdr/blob/master/lib/fcd/fcd_source_c.cc#L255

**Comment by yarda** [comment]
It seems they store it as int:
https://github.com/osmocom/gr-osmosdr/blob/master/lib/fcd/fcd_source_c.h#L87

But return it later as double:
https://github.com/osmocom/gr-osmosdr/blob/master/lib/fcd/fcd_source_c.cc#L270

The gr-osmosdr change should be trivial and the gr-osmosdr API wouldn't change.

**Comment by dl1ksv** [comment]
@yarda can you point me to the gr-funcube patch for gr-osmosdr?
I think, to switch from int to double should be no big deal, but perhaps I'll offer both in the gnuradio module.

**Comment by yarda** [comment]
@dl1ksv I am using the following patch in the Fedora downstream for the vanilla gr-osmosdr:
https://src.fedoraproject.org/rpms/gr-osmosdr/blob/rawhide/f/gr-osmosdr-0.2.3-gr-funcube.patch

I am still trying to get it to the gr-osmosdr upstream, but they seems silent :)

**Comment by dl1ksv** [comment]
@yarda I just uploaded a ppm_double branch.
Now ppm is of type double. I had to change frequency to double, too. I tested these change with gnuradio and it works for the fcd and the fcdpp dongle.

After modifying your patch version of gr-osmosdr it works with gqrx as well.
I changed the type of _correct to double in fcd_source.h and removed the casting to float of freq in fcd_source.cc (line 240 and 243.

Could you please check this branch. If it works well, I'll merge it to main.

**Comment by yarda** [comment]
@dl1ksv thanks. I checked only with the gqrx and fcdpp and it seems it's working perfectly.

**Comment by yarda** [comment]
FYI gr-osmosdr upstream tickets:
https://osmocom.org/issues/5445
https://osmocom.org/issues/5460

**Comment by dl1ksv** [comment]
Thanks for testing.
To get the most benefit you should add 

diff --git a/lib/fcd/fcd_source_c.cc b/lib/fcd/fcd_source_c.cc
index 854e4c0..5eea677 100644
--- a/lib/fcd/fcd_source_c.cc
+++ b/lib/fcd/fcd_source_c.cc

@@ -237,10 +237,10 @@ osmosdr::freq_range_t fcd_source_c::get_freq_range( size_t chan )
 double fcd_source_c::set_center_freq( double freq, size_t chan )
 {
   if ( FUNCUBE_V1 == _type )
-    _src_v1->set_freq( float(freq) );
+    _src_v1->set_freq( freq );
 
   if ( FUNCUBE_V2 == _type )
-    _src_v2->set_freq( float(freq) );
+    _src_v2->set_freq( freq );
 
   _freq = freq;

Otherwise 
(double) freq -> (float) freq -> (double) freq
which may lead to loose some significant digits of freq.

**Comment by yarda** [comment]
Thanks, updated.

**Comment by yarda** [comment]
Everything seems to work, closing, thanks.
